---
# Copyright 2016, IBM US, Inc.
#
# xorg workaround
#

#- name: systemctl set-default
#  shell: "systemctl set-default multi-user"
#  become: yes
#  become_method: sudo
#- name: Create mapd user
#  user: 
#    name: mapd
#    comment: "mapd default user" 

#- name: Create /opt/mapd directory
#  file: 
#    path: /opt/mapd
#    state: directory
#    owner: mapd


# copy reference cuda repository from local machine over to target nodes
- name: Copy mapd apt list file
  copy: src="mapd.list" dest="/etc/apt/sources.list.d/mapd.list"
  become: yes
  become_method: sudo 

- name: Pull mapd gpg key
  shell: "curl https://releases.mapd.com/GPG-KEY-mapd | sudo apt-key add -"
  become: yes
  become_method: sudo
 
- name: Update repositories cache and install "mapd" package
  apt:
    name: mapd
    update_cache: yes

- name: Execute mapd_setup.sh script
  script: scripts/setup_mapd.sh
  become: yes
  become_method: sudo 
...
