#!/bin/bash
#Check activation files
check_rc=0
while read cfile; do
        echo "Trying: $cfile"
        $cfile $1
        temp_rc=$?
        if [[ $temp_rc -ne 0 ]]; then
                echo "ERROR: Check $cfile returned error code $temp_rc"
        fi
        check_rc=$(( $check_rc + $temp_rc ))
done <  <(ls -1 scripts/deploychecks/*_check 2>/dev/null | sort)

exit $check_rc
